module Decks.MockData exposing (..)

import Decks.Deck as Deck exposing (Deck, DeckId(..))
import Decks.User as User exposing (User, UserId(..), Role(..))
import Card exposing (Card, CardId(..), CardType(..))
import CardExtra
import CardSet

user_asier : User
user_asier =
    { id = UserId 1
    , name = "Asier"
    , bio = "Mock account to test the UI"
    , role = Role_Regular
    }

deck_stark_siege : Deck
deck_stark_siege =
    let
        empty = Deck.empty
        card_with_id : CardId -> Card
        card_with_id id = CardExtra.card_with_id id
            |> Maybe.withDefault { id = CardId "", name = "", card_type = Card.CardType_Attachment, set = CardSet.Set_Core, number = 1, quantity = 1, limit = 3, legality_joust = Card.Legality_Legal, legality_melee = Card.Legality_Legal, illustrator = "", house = [], legal_in_houses = [], unique = True, rules_text = Nothing, flavor_text = Nothing, cost = Nothing, icons = [], crest = [], traits = [], strength = Nothing, income = Nothing, initiative = Nothing, claim = Nothing, influence = Nothing, erratas = [], duplicate_id = Nothing }
    in
        { empty | id = DeckId 1, author = UserId 1, name = "Stark Asedio", description = "Mazo de asedio de Invernalia. Midrange. Va de controlar la mesa.", joust = True }
            |> Deck.add_card (card_with_id <| CardId "core_209")
            |> Deck.add_card (card_with_id <| CardId "low_48")
            |> Deck.add_card (card_with_id <| CardId "asots_59")
            |> Deck.add_card (card_with_id <| CardId "core_206")
            |> Deck.add_card (card_with_id <| CardId "core_200")
            |> Deck.add_card (card_with_id <| CardId "core_201")
            |> Deck.add_card (card_with_id <| CardId "qod_49")
            |> Deck.add_card (card_with_id <| CardId "low_53")
            |> Deck.add_card (card_with_id <| CardId "low_55")
            |> Deck.add_card (card_with_id <| CardId "pots_38")
            |> Deck.add_card (card_with_id <| CardId "ator_83")
            |> Deck.add_card (card_with_id <| CardId "ator_83")
            |> Deck.add_card (card_with_id <| CardId "ator_83")
            |> Deck.add_card (card_with_id <| CardId "dotn_81")
            |> Deck.add_card (card_with_id <| CardId "ator_16")
            |> Deck.add_card (card_with_id <| CardId "ator_16")
            |> Deck.add_card (card_with_id <| CardId "ator_16")
            |> Deck.add_card (card_with_id <| CardId "low_8")
            |> Deck.add_card (card_with_id <| CardId "core_2")
            |> Deck.add_card (card_with_id <| CardId "core_29")
            |> Deck.add_card (card_with_id <| CardId "core_29")
            |> Deck.add_card (card_with_id <| CardId "core_29")
            |> Deck.add_card (card_with_id <| CardId "kotst_45")
            |> Deck.add_card (card_with_id <| CardId "kotst_45")
            |> Deck.add_card (card_with_id <| CardId "kotst_45")
            |> Deck.add_card (card_with_id <| CardId "low_18")
            |> Deck.add_card (card_with_id <| CardId "low_18")
            |> Deck.add_card (card_with_id <| CardId "low_18")
            |> Deck.add_card (card_with_id <| CardId "low_47")
            |> Deck.add_card (card_with_id <| CardId "low_47")
            |> Deck.add_card (card_with_id <| CardId "low_47")
            |> Deck.add_card (card_with_id <| CardId "kotse_38")
            |> Deck.add_card (card_with_id <| CardId "kotse_38")
            |> Deck.add_card (card_with_id <| CardId "kotse_38")
            |> Deck.add_card (card_with_id <| CardId "kl_2")
            |> Deck.add_card (card_with_id <| CardId "kl_2")
            |> Deck.add_card (card_with_id <| CardId "kl_2")
            |> Deck.add_card (card_with_id <| CardId "ator_103")
            |> Deck.add_card (card_with_id <| CardId "ator_103")
            |> Deck.add_card (card_with_id <| CardId "ator_103")
            |> Deck.add_card (card_with_id <| CardId "bwb_21")
            |> Deck.add_card (card_with_id <| CardId "bwb_21")
            |> Deck.add_card (card_with_id <| CardId "bwb_21")
            |> Deck.add_card (card_with_id <| CardId "atoc_82")
            |> Deck.add_card (card_with_id <| CardId "atoc_82")
            |> Deck.add_card (card_with_id <| CardId "atoc_82")
            |> Deck.add_card (card_with_id <| CardId "kotse_45")
            |> Deck.add_card (card_with_id <| CardId "kl_1")
            |> Deck.add_card (card_with_id <| CardId "bwb_101")
            |> Deck.add_card (card_with_id <| CardId "atoc_101")
            |> Deck.add_card (card_with_id <| CardId "kl_61")
            |> Deck.add_card (card_with_id <| CardId "kl_97")
            |> Deck.add_card (card_with_id <| CardId "kr_54")
            |> Deck.add_card (card_with_id <| CardId "kr_93")
            |> Deck.add_card (card_with_id <| CardId "cad_18")
            |> Deck.add_card (card_with_id <| CardId "acoa_101")
            |> Deck.add_card (card_with_id <| CardId "acoa_101")
            |> Deck.add_card (card_with_id <| CardId "w_92")
            |> Deck.add_card (card_with_id <| CardId "kl_77")
            |> Deck.add_card (card_with_id <| CardId "acoa_65")
            |> Deck.add_card (card_with_id <| CardId "low_22")
            |> Deck.add_card (card_with_id <| CardId "pots_37")
            |> Deck.add_card (card_with_id <| CardId "soo_21")
            |> Deck.add_card (card_with_id <| CardId "soo_1")
            |> Deck.add_card (card_with_id <| CardId "pots_39")
            |> Deck.add_card (card_with_id <| CardId "core_5")
            |> Deck.add_card (card_with_id <| CardId "low_7")
            |> Deck.add_card (card_with_id <| CardId "core_139")
            |> Deck.add_card (card_with_id <| CardId "qod_43")

deck_bara_knights : Deck
deck_bara_knights =
    let
        empty = Deck.empty
        card_with_id : CardId -> Card
        card_with_id id = CardExtra.card_with_id id
            |> Maybe.withDefault { id = CardId "", name = "", card_type = Card.CardType_Attachment, set = CardSet.Set_Core, number = 1, quantity = 1, limit = 3, legality_joust = Card.Legality_Legal, legality_melee = Card.Legality_Legal, illustrator = "", house = [], legal_in_houses = [], unique = True, rules_text = Nothing, flavor_text = Nothing, cost = Nothing, icons = [], crest = [], traits = [], strength = Nothing, income = Nothing, initiative = Nothing, claim = Nothing, influence = Nothing, erratas = [], duplicate_id = Nothing }
    in
        { empty | id = DeckId 2, author = UserId 1, name = "Baratheon Caballeros Aggro", description = "Mazo de Baratheon de caballeros. Va de cartas con renombre y ganar muy rápido.", joust = True }
            |> Deck.add_card (card_with_id <| CardId "core_211")
            |> Deck.add_card (card_with_id <| CardId "kotst_39")
            |> Deck.add_card (card_with_id <| CardId "low_52")
            |> Deck.add_card (card_with_id <| CardId "core_201")
            |> Deck.add_card (card_with_id <| CardId "core_194")
            |> Deck.add_card (card_with_id <| CardId "kotse_53")
            |> Deck.add_card (card_with_id <| CardId "bwb_80")
            |> Deck.add_card (card_with_id <| CardId "kotst_49")
            |> Deck.add_card (card_with_id <| CardId "ator_20")
            |> Deck.add_card (card_with_id <| CardId "ator_86")
            |> Deck.add_card (card_with_id <| CardId "ator_86")
            |> Deck.add_card (card_with_id <| CardId "ator_86")
            |> Deck.add_card (card_with_id <| CardId "kotst_40")
            |> Deck.add_card (card_with_id <| CardId "kotst_40")
            |> Deck.add_card (card_with_id <| CardId "kotst_40")
            |> Deck.add_card (card_with_id <| CardId "kotst_18")
            |> Deck.add_card (card_with_id <| CardId "kotst_18")
            |> Deck.add_card (card_with_id <| CardId "kotst_18")
            |> Deck.add_card (card_with_id <| CardId "btns_65")
            |> Deck.add_card (card_with_id <| CardId "btns_65")
            |> Deck.add_card (card_with_id <| CardId "lotr_44")
            |> Deck.add_card (card_with_id <| CardId "lotr_44")
            |> Deck.add_card (card_with_id <| CardId "acoa_62")
            |> Deck.add_card (card_with_id <| CardId "core_79")
            |> Deck.add_card (card_with_id <| CardId "bwb_49")
            |> Deck.add_card (card_with_id <| CardId "kl_66")
            |> Deck.add_card (card_with_id <| CardId "kl_86")
            |> Deck.add_card (card_with_id <| CardId "kotst_5")
            |> Deck.add_card (card_with_id <| CardId "kotst_6")
            |> Deck.add_card (card_with_id <| CardId "kotst_8")
            |> Deck.add_card (card_with_id <| CardId "kotst_9")
            |> Deck.add_card (card_with_id <| CardId "kotst_10")
            |> Deck.add_card (card_with_id <| CardId "w_21")
            |> Deck.add_card (card_with_id <| CardId "w_41")
            |> Deck.add_card (card_with_id <| CardId "w_61")
            |> Deck.add_card (card_with_id <| CardId "soo_5")
            |> Deck.add_card (card_with_id <| CardId "soo_45")
            |> Deck.add_card (card_with_id <| CardId "dotn_105")
            |> Deck.add_card (card_with_id <| CardId "btns_8")
            |> Deck.add_card (card_with_id <| CardId "kr_101")
            |> Deck.add_card (card_with_id <| CardId "core_70")
            |> Deck.add_card (card_with_id <| CardId "asots_67")
            |> Deck.add_card (card_with_id <| CardId "asots_77")
            |> Deck.add_card (card_with_id <| CardId "btns_7")
            |> Deck.add_card (card_with_id <| CardId "ator_64")
            |> Deck.add_card (card_with_id <| CardId "kl_46")
            |> Deck.add_card (card_with_id <| CardId "core_175")
            |> Deck.add_card (card_with_id <| CardId "core_175")
            |> Deck.add_card (card_with_id <| CardId "core_175")
            |> Deck.add_card (card_with_id <| CardId "kotst_48")
            |> Deck.add_card (card_with_id <| CardId "kotst_48")
            |> Deck.add_card (card_with_id <| CardId "kotst_48")
            |> Deck.add_card (card_with_id <| CardId "kotse_30")
            |> Deck.add_card (card_with_id <| CardId "kotse_30")
            |> Deck.add_card (card_with_id <| CardId "kotse_30")
            |> Deck.add_card (card_with_id <| CardId "dotn_6")
            |> Deck.add_card (card_with_id <| CardId "dotn_6")
            |> Deck.add_card (card_with_id <| CardId "dotn_6")
            |> Deck.add_card (card_with_id <| CardId "core_92")
            |> Deck.add_card (card_with_id <| CardId "core_92")
            |> Deck.add_card (card_with_id <| CardId "core_92")
            |> Deck.add_card (card_with_id <| CardId "btns_76")
            |> Deck.add_card (card_with_id <| CardId "core_149")
            |> Deck.add_card (card_with_id <| CardId "qod_43")
            |> Deck.add_card (card_with_id <| CardId "bwb_66")
            |> Deck.add_card (card_with_id <| CardId "kl_106")
            |> Deck.add_card (card_with_id <| CardId "core_94")
            |> Deck.add_card (card_with_id <| CardId "kotst_31")
            |> Deck.add_card (card_with_id <| CardId "kotst_31")

