name: build-page
run-name: ${{ github.actor }} is building the static page from source

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Install Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install Elm
        uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1

      - name: Generate HTML with tags for cards
        run: cargo +nightly -Zscript ./scripts/genhtml.rs ./template.html ./cards.json ./build/card

      - name: Build page
        run: elm make --optimize ./src/Main.elm --output ./build/page.js

      - name: Copy files to build directory
        run: |
          cp ./cards.json ./build/
          cp ./favicon.ico ./build/
          cp ./index.html ./build/
          cp ./main.js ./build/
          cp -a ./fontawesome ./build/fontawesome
          cp -a ./images ./build/images

      - name: Create preview low resolution card images
        run: cargo +nightly -Zscript ./scripts/scale_images.rs ./images/cards/full ./build/images/cards/preview

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 81208e1c136d26e6fbf27f1c07ec0ce6
          projectName: agot-lcg-search
          directory: ./build/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
